version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: node_postgres
    restart: always
    environment:
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nodeapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: node_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
