POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "userName":"prueba",
  "email": "PRUEBA@gmail.com",
  "password": "contras234"
}


###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "userName":"prueba",
  "email": "PRUEBA@gmail.com",
  "password": "contras234"
}

###

POST http://localhost:3000/api/habit/custom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJQUlVFQkFAZ21haWwuY29tIiwidXNlck5hbWUiOiJwcnVlYmEiLCJpYXQiOjE3NDYyODU1NzAsImV4cCI6MTc0NjI4OTE3MH0.nYRpajwPuuD3hM5_da65MJ00e735V8HNmGXanC-NU24

{
  "name": "habito del sabado",
  "description": "desc",
  "frequency": {
    "type": "weekly",
    "days": ["saturday"]
  },
  "icon": "./img",
  "startDate": "2025-04-26T00:00:00.000Z",
  "fieldValues": {"unit": "min", "value": "30"}
}

###

GET http://localhost:3000/api/inicio/principalScr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJQUlVFQkFAZ21haWwuY29tIiwidXNlck5hbWUiOiJwcnVlYmEiLCJpYXQiOjE3NDYyODU1NzAsImV4cCI6MTc0NjI4OTE3MH0.nYRpajwPuuD3hM5_da65MJ00e735V8HNmGXanC-NU24